DROP TABLE IF EXISTS DATASET_REGISTRATION_DATA;
CREATE TABLE DATASET_REGISTRATION_DATA(
	ID bigint(20) NOT NULL AUTO_INCREMENT,
	REGISTRY_ID bigint(20),
	MAJORVERSION int(3),
	MINORVERSION int(3),
	SUBMINORVERSION int(3),
	UUID VARCHAR(40),
	REASON_ID bigint(20),
	STATUS VARCHAR(25),
	PRIMARY KEY (ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE DATASET_REGISTRATION_DATA ADD CONSTRAINT FK_DSR_REG_ID FOREIGN KEY (REGISTRY_ID) REFERENCES REGISTRY (ID);
ALTER TABLE DATASET_REGISTRATION_DATA ADD CONSTRAINT FK_DSR_READSON_ID FOREIGN KEY (REASON_ID) REFERENCES DATASET_DEREGISTRATION_REASON (ID);

ALTER TABLE T_NODE_CREDENTIALS DROP INDEX NODEID;